In [2]:
#Libraries, loops, and lists
#import two standard libraries
import numpy as np
import pandas as pd
# you can use "as" to nickname to libraries

In [3]:
#initialize an array
# make an array of numbers 0 to 100 (exclusive)

random_list = np.arange(stop = 100)

#consult documentation for further function parameters/outputs, etc...

In [4]:
#print is built-in in python

print(random_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [5]:
#A1 use np.arange to create a new list
# called even_list_1 that contains all the even numbers from 0 to 100 (exclusive)

even_list_1 = np.arange(0, 100, 2).tolist()
print(even_list_1)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [6]:
#the [] allows us to access elements from an array 
print(random_list [0])

#use the : operator to access elements a certain range 
print(random_list[5:15])
#note that the last element is exclusive 

#we also just access a number at either end of your list using : to indicate we want Python to go all the way to end
print(random_list[95:])
print(random_list[:5])



0
[ 5  6  7  8  9 10 11 12 13 14]
[95 96 97 98 99]
[0 1 2 3 4]


In [7]:
#A2

#print the element at the 90th index of the array 
ninety_index = random_list [90]
#print the elements from index 10 to index 21
index_ten_to_twenty_one = random_list [10:22]
#print the last ten elements of the array 
last_ten_indices = random_list[90:]


print(random_list [90])
print(random_list[10:22])
print(random_list[90:])

90
[10 11 12 13 14 15 16 17 18 19 20 21]
[90 91 92 93 94 95 96 97 98 99]


In [8]:
#doing mathematical operations on our list
#want the list to start at 1 instead of 0 
#add 1 to each element in the array 

random_list = random_list + 1
print(random_list)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [9]:
#do the same with natural nlog, using np.log command
#take the natural log of each element in the array, and printing the result

print(np.log(random_list))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898 2.99573227 3.04452244 3.09104245 3.13549422 3.17805383
 3.21887582 3.25809654 3.29583687 3.33220451 3.36729583 3.40119738
 3.4339872  3.4657359  3.49650756 3.52636052 3.55534806 3.58351894
 3.61091791 3.63758616 3.66356165 3.68887945 3.71357207 3.73766962
 3.76120012 3.78418963 3.80666249 3.8286414  3.8501476  3.87120101
 3.8918203  3.91202301 3.93182563 3.95124372 3.97029191 3.98898405
 4.00733319 4.02535169 4.04305127 4.06044301 4.07753744 4.09434456
 4.11087386 4.12713439 4.14313473 4.15888308 4.17438727 4.18965474
 4.20469262 4.21950771 4.2341065  4.24849524 4.26267988 4.27666612
 4.29045944 4.30406509 4.31748811 4.33073334 4.34380542 4.35670883
 4.36944785 4.38202663 4.39444915 4.40671925 4.41884061 4.4308168
 4.44265126 4.4543473  4.46590812 4.47733681 4.48863637 4.49980

In [10]:
#boolean indexing can also be performed element-wise across an array
#boolean index array that shwos where all the odds(falses) are:

print(random_list % 2 == 0 )

#taking in the boolean index array into the new array allows us to filter out the falses 
even_list_2 = random_list[random_list % 2 == 0]
print(even_list_2)

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [11]:
#initialize an empty array 
even_list_3 = np.array([])

#for i in range just means for each value (i) in the range from 0 and 101 (exclusive)
for i in range (0,101):
    #we check if the value (i) is even (when divided by 2, remainder = 0 )
    if i % 2 == 0:
        #use the np.append function to apend i since it's even
        even_list_3 = np.append(arr = even_list_3, values = i)
        #notice the append function takes in an array named 'arr' and the value you'd like to append


print(even_list_3)

[  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.
  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.
  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.
  84.  86.  88.  90.  92.  94.  96.  98. 100.]


In [12]:
#make an array of number from 0 to 200 (exclusive)
big_list = np.arange(200)

#multiply numbers resulting in a big list
even_list_4 = [2*x for x in big_list if x <= 50] 
#notice how list comprehsnion allows us to save lines of code
#perform multiple operations

#convert to an array 
even_list_4 = np.array(even_list_4)

print(even_list_4)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [13]:
#A3 
#A3 your code here
test_list = np.array([ -99.52287875, -100.        ,  -99.39794001, -100.        ,
        -99.30103   ,  -99.04575749,  -99.69897   ,  -99.22184875,
        -99.30103   ,  -99.52287875,  -99.30103   ,  -99.09691001,
        -99.04575749,  -99.15490196,  -99.04575749,  -99.52287875,
        -99.69897   ,  -99.52287875,  -99.09691001,  -99.39794001,
        -99.22184875,  -99.69897   ,  -99.22184875,  -99.39794001])


#1. Add 100 to each number in the list
#2. Use np.power()


test_list = test_list + 100
test_list = np.power(10, test_list) #array-wide operation
test_list = np.round(test_list)
print(test_list[:5])

[3. 1. 4. 1. 5.]


In [14]:
#II. Dataframes and Pandas

gapminder = pd.read_csv('gapminder.csv')


In [15]:
#this prints the data in the row at index number 1
print(gapminder.iloc[1])

country      Afghanistan
continent           Asia
year                1957
lifeExp           30.332
pop              9240934
gdpPercap      820.85303
Name: 1, dtype: object


In [16]:
#print the data in the first 5 rows
print(gapminder.head(5))


       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106


In [17]:
#print using iloc
print(gapminder.iloc [0:5])

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106


In [18]:
#print specific columns: print the data in the column continent
print(gapminder.loc[: , 'continent'])

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...  
1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, Length: 1704, dtype: str


In [19]:
#another way to print the data in the column continent
print(gapminder['continent'])

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...  
1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, Length: 1704, dtype: str


In [20]:
#print the data in both columns continent and country 
print(gapminder[['continent', 'country']])

     continent      country
0         Asia  Afghanistan
1         Asia  Afghanistan
2         Asia  Afghanistan
3         Asia  Afghanistan
4         Asia  Afghanistan
...        ...          ...
1699    Africa     Zimbabwe
1700    Africa     Zimbabwe
1701    Africa     Zimbabwe
1702    Africa     Zimbabwe
1703    Africa     Zimbabwe

[1704 rows x 2 columns]


In [21]:
#filtering non-needed data

print((gapminder ['year'] >= 1980))

#boolean index gapminder based on the combined (&) conditions on the 'year' column
filtered_gapminder = gapminder[(gapminder ['year'] >= 1980) & (gapminder['year'] <= 2000)]

0       False
1       False
2       False
3       False
4       False
        ...  
1699     True
1700     True
1701     True
1702     True
1703     True
Name: year, Length: 1704, dtype: bool
